# Di2 – Eigen Docker image experiment
FROM python:3.9-slim

# Werkdirectory in de container
WORKDIR /app

# Kopieer de app in de image
COPY app.py /app/app.py

# Command dat uitgevoerd wordt als de container start
CMD ["python", "app.py"]
