pipeline {
    agent any

    stages {
        stage('Install dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Lint') {
            steps {
                sh 'flake8 . || true'
            }
        }
        stage('Test') {
            steps {
                sh 'pytest'
            }
        }
    }
}
